name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: base
        uses: docker/build-push-action@v3
        with:
          context: ./base
          tags: timche/csgo
          push: false
      - name: sourcemod
        uses: docker/build-push-action@v3
        with:
          context: ./sourcemod
          tags: timche/csgo:sourcemod
          push: false
      - name: pug-practice
        uses: docker/build-push-action@v3
        with:
          context: ./pug-practice
          tags: timche/csgo:pug-practice
          push: false
