name: docker

on:
  release:
    types: [released]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: base
        uses: docker/build-push-action@v3
        with:
          context: ./base
          tags: maxaucube/docker-vietnam:latest,maxaucube/docker-vietnam:${{ github.event.release.tag_name }}
          push: true
      - name: sync-description-with-readme
        uses: peter-evans/dockerhub-description@v3.1.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: maxaucube/docker-vietnam
