name: upgrade-mods

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run upgrade-mods
        env:
          OCTOKIT_AUTH_TOKEN: ${{ secrets.OCTOKIT_AUTH_TOKEN }}
